[package]
name = "oci"
version = "0.2.0"
authors = [
    "Vishvananda Ishaya Abrams <vish.ishaya@oracle.com>",
    "Bernhard Schuster <bernhard@ahoi.io>",
]
edition = "2018"

[dependencies]
serde = "1"
serde_json = "1"
serde_derive = "1"
thiserror = "1"
