[package]
name = "railcar"
version = "1.0.4"
authors = ["Vishvananda Ishaya Abrams <vish.ishaya@oracle.com>"]
build = "build.rs"

[dependencies]
caps = "0.2"
clap = "2.24"
error-chain = "0.12"
lazy_static = "1"
libc = "0.2"
log = {version = "0.4", features = ["release_max_level_info"] }
nix = "0.11.0"
num-traits = "^0.2.5"
oci = { path = "oci" }
prctl = "1"
scopeguard = "^0.3.3"
seccomp-sys = "^0.1.2"

[features]
nightly = []

[profile.release]
lto = true
panic = 'abort'
