
FROM ekidd/rust-musl-builder

MAINTAINER Bernhard Schuster "bernhard@ahoi.io"

USER root

RUN apt-get update -y && apt-get install -y autoconf automake libtool sed && ln -s /bin/sed /usr/bin/sed && rm -rf /var/cache

USER rust

RUN rustup toolchain install \
        stable-x86_64-unknown-linux-musl \
        beta-x86_64-unknown-linux-musl \
        nightly-x86_64-unknown-linux-musl

ENV CMAKE_MAKE_PROGRAM=make